ML-507 Gaussian Process Regression
hpcc-systems/GaussianProcessRegression pull request #1
Opened 2022-01-12 17:43 UTC by lilyclemson

Random Fourier Features accelerated Gaussian Process Regressor

2022-01-12 18:37 UTC, RogerDev commented on GPRI.ecl
> +    * @return rst GPR model
Where is GPR model defined.  Should be noted here.

2022-01-12 18:51 UTC, RogerDev requested changes
Almost there. A few comments, mostly regarding doc.

2022-01-12 18:51 UTC, RogerDev commented on GPRI.ecl
> +    * @return rst prediction result
Leave name out of @return statements.  Include expected format..  Should be (e.g., "@return prediction result in NumericField format")

2022-01-12 18:51 UTC, RogerDev commented on README.md
> +Random Fourier Features accelerated Gaussian Process Regressor
Provide an overview of the bundle.  Specifically, The purpose and constraints of the bundleshould be discussed, and the available "public" modules should be defined and described.  For example:

GPRI is the main module that allows fitting of models and making predictions based on the fitted model.
Types provides ...
Usage examples can be found in the Test folder
etc.

Need to acknowledge the python module that we built it from.

Installation instructions:

Do we have any installation dependencies?
ecl bundle install ....

2022-01-12 18:51 UTC, RogerDev commented on eclcc.log
> +00000000 PRG 2022-01-12 12:39:17 26888  4004 "Loading plugin C:\Program Files\HPCCSystems\8.2.18\clienttools\plugins\auditlib.dll[lib_auditlib] version = AUDITLIB 1.0.1"
This file should be removed, and supress via .gitignore

2022-01-12 18:51 UTC, RogerDev commented on GPRI.ecl
> +
Doesn't look like this bundle supports the Myriad interface.  We should note whether or not each bundle supports it, here or in README.

2022-01-12 18:51 UTC, RogerDev commented on GPRI.ecl
> +      RETURN SORT(rst, id);
Should sort by number as well, I think.

2022-01-12 18:51 UTC, RogerDev commented on GPRI.ecl
> +    * @return rst GPR model
Leave out return variable name on @return. Where is GPR model defined. Should be noted here.

2022-01-12 20:29 UTC, lilyclemson commented
@RogerDev  changes are made based on the comments. Please review.

2022-01-27 22:23 UTC, RogerDev approved these changes
@ghalliday @lilyclemson   This is good to merge

2022-02-04 10:30 UTC, ghalliday approved these changes
@lilyclemson a few minor typos, I would merge if you don't mind, or you can fix first

2022-02-04 10:30 UTC, ghalliday commented on GPRI.ecl
> + * Three functoins are available for the users: getSession, fit and predict.
typo: functions

2022-02-04 10:30 UTC, ghalliday commented on GPRI.ecl
> + *   * Predict funcion uses the trained GPR model to make predictions for the new observations.
typo: function

2022-02-04 10:30 UTC, ghalliday commented on README.md
> +The module GPRI is the main ECL interface. Three functoins are available to the users: getSession,
same typos of "functions"

2022-02-04 10:30 UTC, ghalliday commented on README.md
> +This bunel is built upon the orignal python implementaton of GPR module from below source:
typo: bundle

2022-02-04 10:30 UTC, ghalliday commented on Test/test.ecl
> +// Python versoin GPR
typo: version

2022-02-04 13:59 UTC, lilyclemson commented
@ghalliday I fixed the typos. Please review.

2022-02-04 14:28 UTC, merged